project:
  type: website
  output-dir: _site

website:
  title: "🧠 The Memory Project"
  navbar:
    tools:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sulaimanhayek
  page-navigation: true
format:
  html:
    theme:
      - cosmo
    css: styles.css



